<?php
/**
 * IDE: PhpStorm
 * Project: esser
 * Filename: ${FILE_NAME}
 * User: Gheorghita Mutu
 * Email: gheorghitamutu@gmail.com
 * Date: 4/5/2018
 * Time: 2:27 PM
 */
?>

<!DOCTYPE html>
<html>
<head>
    <link rel="icon" href="/favicon.png" />
    <link rel="stylesheet" href="/bg_style.css" />
    <meta charset="utf-8">
    <meta name="author" content="Bugeag George Tiberiu">
    <meta name="description" content="Web Technologies Project">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Esser</title>
</head>
<body>