<?php
/**
 * IDE: PhpStorm
 * Project: esser
 * Filename: index.phtml
 * User: Gheorghita Mutu
 * Email: gheorghitamutu@gmail.com
 * Date: 4/5/2018
 * Time: 2:15 PM
 */
?>

<?php include VIEW . 'home/header.phtml';?>

<br><br><br><br>
<div class="main-container">
    <div class="main-box">
        <h1 class="main-text"> Welcome to <?php echo APP_TITLE ?> </h1>
        <br>
        <button type="button" class="main-btn" onclick="window.location.assign('/login')">Login</button>
        <button type="button" class="main-btn" onclick="window.location.assign('/register')">Register</button>
        <br>
    </div>
</div>

<?php include VIEW . 'home/footer.phtml';?>

