<?php
/**
 * IDE: PhpStorm
 * Project: esser
 * Filename: index.phtml
 * User: Gheorghita Mutu
 * Email: gheorghitamutu@gmail.com
 * Date: 4/5/2018
 * Time: 2:15 PM
 */
?>

<?php include VIEW . 'home/header.phtml';?>
<?php echo "                  ".hash('sha512', 'POIY!@&(#*!P H"poe][Lk\'poPIE"!@#IE[2k"E!@KEP"ep[l1}@)#(joh!@#&($0a44909f90d1dd47bf42bbb6d107af6166c7f8c2853ca42ee50e4865541d04e74b67f3a89170e010eea2be2441130b5f9d36e00d4746496aaa7b2f0d547253120a44909f90d1dd47bf42bbb6d107af6166c7f8c2853ca42ee50e4865541d04e74b67f3a89170e010eea2be2441130b5f9d36e00d4746496aaa7b2f0d54725312'); ?>
<div class="main-container">
    <div class="main-box">
        <h1 class="main-text"> Welcome to <?php echo $this->view_data["apptitle"] ?> </h1>
        <h2 class="main-text"> What do you want to do? </h2>
        <button type="button" class="main-btn" onclick="window.location.assign('/register')">Register</button>
        <button type="button" class="main-btn" onclick="window.location.assign('/login')">Login</button>
    </div>
</div>

<?php include VIEW . 'home/footer.phtml';?>

