<?php include VIEW . 'admincp/header.phtml';?>

<?php include VIEW . 'admincp/menu/header_bar.phtml';?>
<div class="admcp-tables-body">
    <?php include VIEW . 'admincp/menu/menu.phtml';?>
    <div class="admcp-rt-box">
        <div class="admcp-rt-cnt-box">
            <div class="admcp-rt-content">
                <h3 class="adm-rt-title"> Search logs of a specifc product </h3>
                <form class="srch-layout">
                    <input class="adm-srch-box" required="required" placeholder="Insert Product">
                    <button type="submit" class="admcp-srch-btn"> Search </button>
                </form>
            </div>
        </div>
        <div class="admcp-rt-result-box">
            <div class="admcp-rt-content">
                <h3 class="adm-rt-title"> Logs List </h3>
                <div class="flex-table">
                    <div class="flex-table-head">
                        <div class="flex-table-row">
                            <div class="flex-table-th"> Product </div>
                            <div class="flex-table-th"> Date </div>
                            <div class="flex-table-th"> Action Info </div>
                            <div class="flex-table-th"> Quantifier </div>
                            <div class="flex-table-th"> Account </div>
                            <div class="flex-table-th"> IP </div>
                        </div>
                    </div>
                    <div class="flex-table-body">
                        <?php foreach ($this->param[1] as $rows) {
                            echo "<div class=\"flex-table-row\">";
                            foreach ($rows as $row => $value) {
                                echo "<div class=\"flex-table-td\"> $value </div >";
                            }
                            echo "</div >";
                        }?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php include VIEW . 'admincp/footer.phtml';?>