<?php include VIEW . 'admincp/header.phtml';?>

<?php include VIEW . 'admincp/menu/header_bar.phtml';?>

<div class="admcp-tables-body">
    <?php include VIEW . 'admincp/menu/menu.phtml';?>
            <div class="admcp-rt-box">
                <div class="admcp-rt-cnt-box">
                    <div class="admcp-rt-content">
                        <h3 class="adm-rt-title"> Search login logs of a specific user </h3>
                        <form class="srch-layout" method="POST" action="/admincp/userlogs/searchuserlogs">
                            <input class="adm-srch-box" name="searchuserloginlogs" required="required" value="" placeholder="Insert User Here">
                            <button type="submit" class="admcp-srch-btn"> Search </button>
                        </form>
                    </div>
                </div>
                <div class="admcp-rt-result-box">
                    <div class="admcp-rt-content">
                        <h3 class="adm-rt-title"> Logs List </h3>                    
                        <div class="flex-table">
                            <div class="flex-table-head">
								<div class="flex-table-row">
									<div class="flex-table-th">Account</div>
									<div class="flex-table-th">Date</div>
									<div class="flex-table-th">Action Info</div>
									<div class="flex-table-th">IP</div>
								</div>								
                            </div>
                            <div class="flex-table-body">
                                <?php
                                for ($i = 0; $i < count($this->view_data['usersloginlogs']); ++$i)
                                {
                                    echo
                                "<div class=\"flex-table-row\">" . PHP_EOL .
									"<div class=\"flex-table-td\">" . $this->view_data['usersloginlogs'][$i]['userName'] .  "</div>" . PHP_EOL .
									"<div class=\"flex-table-td\">" . $this->view_data['usersloginlogs'][$i]['datetime'] .  "</div>" . PHP_EOL .
									"<div class=\"flex-table-td\">" . $this->view_data['usersloginlogs'][$i]['action'] .  "</div>" . PHP_EOL .
									"<div class=\"flex-table-td\">" . $this->view_data['usersloginlogs'][$i]['sourceIP'] .  "</div>" . PHP_EOL .
								"</div>" . PHP_EOL;
								}
                                ?>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
        </div>

<?php include VIEW . 'admincp/footer.phtml';?>
