<?php include VIEW . 'admincp/header.phtml';?>

<?php include VIEW . 'admincp/menu/header_bar.phtml';?>

<div class="admcp-tables-body">
    <?php include VIEW . 'admincp/menu/menu.phtml';?>
            <div class="admcp-rt-box">
                <div class="admcp-rt-cnt-box">
                    <div class="admcp-rt-content">
                        <h3 class="adm-rt-title"> Search logs from and to a specific date </h3>
                        <form class="srch-layout">
                            <input class="adm-srch-box" required="required" placeholder="Insert Start Date">
                            <input class="adm-srch-box" required="required" placeholder="Insert End Date">
                            <button type="submit" class="admcp-srch-btn"> Search </button>
                        </form>
                    </div>
                </div>
                <div class="admcp-rt-result-box">
                    <div class="admcp-rt-content">
                        <h3 class="adm-rt-title"> Logs List </h3>                    
                        <div class="flex-table">
                            <div class="flex-table-head">
								<div class="flex-table-row">
									<div class="flex-table-th">Account</div>
									<div class="flex-table-th">Date</div>
									<div class="flex-table-th">Action Info</div>
									<div class="flex-table-th">IP</div>
								</div>								
                            </div>
                            <div class="flex-table-body">
                                <div class="flex-table-row"> 
									<div class="flex-table-td"> Edward </div> 
									<div class="flex-table-td"> 19/03/2018 22:16:43.850 </div>  
									<div class="flex-table-td"> User logged in </div>  
									<div class="flex-table-td"> 162.163.235.18 </div> 
								</div>
								<div class="flex-table-row"> 
									<div class="flex-table-td"> Edward </div> 
									<div class="flex-table-td"> 19/03/2018 23:43:31.600 </div>  
									<div class="flex-table-td"> User Logged Out </div>  
									<div class="flex-table-td"> 162.163.235.18 </div> 
								</div>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
        </div>

<?php include VIEW . 'admincp/footer.phtml';?>
