<?php include VIEW . 'home/header.phtml';?>

<div class="main-container">
    <div class="lgn-box">
        <h1 class="main-text"> Recover My Password </h1>
        <p class="main-text"> The request couldn't be proccesed due to technical issues. </p>
        <button type="button" class="lgn-view-btn" onclick="window.location='/login/forgot'">Retry</button>
        <button type="button" class="lgn-view-btn" onclick="window.location='/'">Return</button>
    </div>
</div>

<?php include VIEW . 'home/footer.phtml';?>