<?php include VIEW . 'home/header.phtml';?>

<div class="main-container">
    <div class="lgn-box">
        <h1 class="main-text"> Recover My Password </h1>
        <form class="lgn-form" action="/login/forgot/check" method="POST">
            <p class="main-text"> Type in your email </p>
            <br>
            <input class="fill-box" type="text" name="email" value="" placeholder="Enter Your Email" required="required"/>
		   	<input type="submit" class="lgn-view-btn" value="Submit">
            <button type="button" class="lgn-view-btn" onclick="window.location='/'">Cancel</button>
		</form>
    </div>
</div>

<?php include VIEW . 'home/footer.phtml';?>