<?php include VIEW . 'admincp/header.phtml';?>

<?php include VIEW . 'admincp/menu/header_bar.phtml';?>

    <div class="admcp-tables-body">
        <?php include VIEW . 'admincp/menu/menu.phtml';?>
            <div class="admcp-rt-box">
                <div class="admcp-rt-cnt-box">
                    <div class="admcp-rt-content">
                        <h3 class="adm-rt-title"> User Account Editor </h3>
                        <form class="srch-layout">
                            <input class="adm-srch-box" required="required" placeholder="Insert User Account">
                            <button type="submit" class="admcp-srch-btn"> Search </button>
                        </form>
                    </div>
                </div>
                <div class="admcp-rt-result-box">
                    <div class="admcp-rt-content">
                        <h3 class="adm-rt-title"> User Account Details </h3>
                        <form type="POST" class="usr-edit-form">
                            <fieldset>
                            <legend></legend>    
                                <div class="ctrl-group">                                
                                    <label> Account Name </label> <input type="text" name="Username" id="acc-username" value="<?php echo (!empty($this->view_data['userToEdit'])) ? $this->view_data['userToEdit']['userName'] : ''; ?>">
                                </div>
                                <div class="ctrl-group">                                
                                    <label> Account Level </label> <input type="text" name="AccLevel" id="acc-level" value="<?php echo (!empty($this->view_data['userToEdit'])) ? $this->view_data['userToEdit']['userType'] : ''; ?>">
                                </div>
                                <div class="ctrl-group"> 
                                    <label> Account Email </label> <input type="email" name="AccEmail" id="acc-email" value="<?php echo (!empty($this->view_data['userToEdit'])) ? $this->view_data['userToEdit']['userEmail'] : ''; ?>">
                                </div>
                                <div class="ctrl-group"> 
                                    <label> New Password </label> <input type="password" name="NewPswd" id="acc-password" value="" placeholder="Insert New Password">
                                </div>
                            </fieldset>
                            <button type="button" class="admcp-save-btn" onclick="editUser('Edward')"> Save </button>
                            <button type="button" class="admcp-save-btn" onclick="window.location='editor'"> Cancel </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

<?php include VIEW . 'admincp/footer.phtml';?>