<?php include VIEW . 'admincp/header.phtml';?>

<?php include VIEW . 'admincp/menu/header_bar.phtml';?>

<div class="admcp-tables-body">
    <?php include VIEW . 'admincp/menu/menu.phtml';?>
            <div class="admcp-rt-box">
                <div class="admcp-rt-cnt-box">
                    <div class="admcp-rt-content">
                        <h3 class="adm-rt-title"> User Management </h3>
                        <div class="flex-table">
                            <div class="flex-table-head">
                                <div class="flex-table-row">
                                    <div class="flex-table-th"> Username </div>
                                    <div class="flex-table-th"> Joined Date </div>
                                    <div class="flex-table-th"> Account Level </div>
                                    <div class="flex-table-th"> Edit </div>
                                    <div class="flex-table-th"> Delete </div>
                                    <div class="flex-table-th"> Approve/Suspend </div>
                                </div>
                            </div>
                            <div class="flex-table-body">
                                <div class="flex-table-row">
                                    <div class="flex-table-td"> Edward </div>
                                    <div class="flex-table-td"> 28/02/2018 </div>
                                    <div class="flex-table-td"> Admin </div>
                                    <div class="flex-table-td"> <form><button type="submit" class="admcp-srch-btn" onclick="window.location='usereditor'"> Edit </button></form></div>
                                    <div class="flex-table-td"> <form><button type="submit" class="admcp-srch-btn" onclick="window.location=''"> <?php echo  "DELETE";//$this->view_data['deleteButton']; ?> </button></form></div>
                                    <div class="flex-table-td"> <form><button type="submit" class="admcp-srch-btn" onclick="window.location=''"> <?php echo "Aprv/Susp";//$this->view_data['approveSuspend']; ?> </button></form></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>            
        </div>

<?php include VIEW . 'admincp/footer.phtml';?>