<?php include VIEW . 'user/header.phtml';?>

    <div id="main-first-row-container">
        <div id="page-title">
            <h1>Reports</h1>
        </div>
    </div>

    <div id="main-second-row-container">
    <div class="container">
        <?php

        if (empty($this->view_data["reports"]))
        {
            echo
            '<div class="container-row">    
                <div class="message">
                    <p>There are no reports!</p>
                </div>
            </div>';

        }
        else
        {
            foreach ($this->view_data["reports"] as $report)
            {
                echo
                    '<div class="message">
                            <p>' . 'Report: ' . ' ' . $report["rCreatedAt"] . '</p>' .
                        '</div>
                         <div class = "message">' .
                            '<form action="/user/reports/download" method="POST">
                                <button type="submit" name="download_report" value="' . $report["reportId"] . '">
                                                Download 
                                </button>
                             </form>'
                        . 
                    '</div>';
            }
        }
        ?>
    </div>
    </div>

<?php include VIEW . 'user/footer.phtml';?>