<?php include VIEW . 'user/header.phtml';?>

    <div id="main-first-row-container">
        <div id="page-title">
            <p>Reports</p>
        </div>
    </div>

    <div id="main-second-row-container">

        <?php

        if (empty($this->view_data["reports"]))
        {
            echo
            '<div class="container-row">    
                <div class="message">
                    <p>There are no reports!</p>
                </div>
            </div>';

        }
        else
        {
            foreach ($this->view_data["reports"] as $report)
            {
                echo
                    '<div class="container-row">
                         <div class="date">
                            <p>'. $report["rCreatedAt"] . '</p>
                        </div>
    
                        <div class="message">
                            <p>' . 'Report: ' . ' ' . $report["reportType"] . '</p>  ' .
                            '<form action="/user/reports/download" method="POST">
                                <button type="submit" name="download_report" value="' . $report["reportId"] . '">
                                                Download 
                                </button>
                             </form>'

                        . '</div>
                    </div>';
            }
        }
        ?>

    </div>

<?php include VIEW . 'user/footer.phtml';?>