<?php include VIEW . 'home/header.phtml';?>

    <div class="main-container">
        <div class="lgn-box">
            <h1 class="main-text"> Registration Failed! </h1>
            <br />
            <p class="main-text">
                Your registration request couldn't be procesed due to
                <?php
                    echo
                    ((isset($_SESSION["registration_wrong_pass_repeat"]) &&
                    $_SESSION["registration_wrong_pass_repeat"] === true) ?
                    'invalid password repeat! Please try again and make sure password matches!' :
                    'technical issues!');
                ?>
            </p>
            <button type="button" class="lgn-view-btn" onclick="window.location='/register'">Retry</button>
            <button type="button" class="lgn-view-btn" onclick="window.location='/'">Home</button>
        </div>
    </div>

<?php include VIEW . 'home/footer.phtml';?>