<!DOCTYPE html>
<html>
	<head>
        <link rel="icon" href="/assets/normal/images/favicon.png" />
		<link rel="stylesheet" href="/assets/normal/css/bg_style.css" />
		<meta charset="utf-8">
		<meta name="author" content="Bugeag George Tiberiu">
		<meta name="description" content="Web Technologies Project">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Esser</title>
	</head>
	<body>
        <div class="main-container">         
            <div class="lgn-box">
                <h1 class="main-text"> Registration Failed! </h1>
                <br />
                <p class="main-text"> Your registration request couldn't be procesed due either invalid or duplicated submited data, or other technical issues such as time-outs, corrupted data, etc! </p>
                <button type="button" class="lgn-view-btn" onclick="window.location='view.register.html'">Retry</button>
                <button type="button" class="lgn-view-btn" onclick="window.location='/index.html'">Home</button>             
            </div>
        </div> 
	</body>
</html>