<?php include VIEW . 'home/header.phtml';?>

    <div class="main-container">
        <div class="lgn-box">
            <h1 class="main-text"> Registration Failed! </h1>
            <br />
            <p class="main-text"> Your registration request couldn't be procesed due either invalid or duplicated submited data, or other technical issues such as time-outs, corrupted data, etc! </p>
            <button type="button" class="lgn-view-btn" onclick="window.location='/register'">Retry</button>
            <button type="button" class="lgn-view-btn" onclick="window.location='/'">Home</button>
        </div>
    </div>

<?php include VIEW . 'home/footer.phtml';?>