<?php include VIEW . 'home/header.phtml';?>

    <div class="main-container">
        <div class="lgn-box">
            <h1 class="main-text"> Registration Completed! </h1>
            <br />
            <p class="main-text"> Your registration request was successful! Now you need to wait for an administrator to validate it! </p>
            <button type="button" class="lgn-view-btn" onclick="window.location='/'">Home</button>
        </div>
    </div>

<?php include VIEW . 'home/footer.phtml';?>