<?php include VIEW . 'home/header.phtml';?>

    <div class="main-container">
        <div class="lgn-box">
            <h1 class="main-text"> Problem encountered! </h1>
            <br />
            <p class="main-text"> Your account is pending approval or it is suspended.
                Please contact an administrator for further details! </p>
            <button type="button" class="lgn-view-btn" onclick="window.location='/'">Home</button>
        </div>
    </div>

<?php include VIEW . 'home/footer.phtml';?>