<?php include VIEW . 'user/header.phtml';?>

    <html>
        <head>
            <link rel="stylesheet" type="text/css" href="/resources/css/user/user-manager.css">
			<script src="/resources/js/user-manager.js"></script>
        </head>
        <body>
			<div class="main" >
				<div class="nested">
					<div>Choose the user group</div>
                        <?php
                        $groups = $this->view_data['memberGroup'];
                        foreach($groups as $group) {
                            $string = str_replace(' ', '', $group['userGroup']);
                            echo "<button type=\"submit\" class=\"menu-button\" onClick='function" . $string . "()'".">" . $group['userGroup'] . "</button>";
                            }
                        ?>
				</div>
			</div>
			
        </body>
    </html>

<?php include VIEW . 'user/footer.phtml';?>