<?php include VIEW . 'user/header.phtml';?>

    <html>
        <head>
            <title>EsseR - Manage users of the group</title>
            <link rel="stylesheet" type="text/css" href="/resources/css/user/user-manager.css">
        </head>
        <body>
			<div class="main">
				<div class="nested">
					<div>Choose the user group</div>
					<div>Group 1</div>
					<div>Group 2</div>
					<div>Group 3</div>
				</div>
			</div>
        </body>
    </html>

<?php include VIEW . 'user/footer.phtml';?>