<?php include VIEW . 'user/header.phtml';?>

    <html>
        <head>
            <title>EsseR - Manage users of the group</title>
            <link rel="stylesheet" type="text/css" href="/resources/css/user/user-manager.css">
			<script src="/resources/js/user-manager.js"></script>
        </head>
        <body>
        <div class="page-title">Choose one of the user groups</div>
			<div class="main-frame">
                <div class="group-list">
                    <?php
                    $groups = $this->view_data['memberGroup'];
                    foreach($groups as $group) {
                        $string = str_replace(' ', '', $group['userGroup']);
                        echo "<button href=\"#\" type=\"submit\" class=\"group-list-button\" >" . $group['userGroup'] . "</button>";

                    }
                    ?>
                </div>
                <div class="group-display">
                    <div class="group-display-button">Add new user</div>
                </div>
            </div>
        </body>
    </html>

<?php include VIEW . 'user/footer.phtml';?>