<?php
/**
 * Created by PhpStorm.
 * User: ghita
 * Date: 5/26/2018
 * Time: 3:28 PM
 */ ?>

    <div class="admcp-left-bar">
        <div class="admc-left-menu">
            <button type="button" class="admcp-menu-option" onclick="window.location='dashboard'"> Dashboard </button>
            <button type="button" class="admcp-menu-option" onclick="window.location='manager'"> Manage Users </button>
            <button type="button" class="admcp-menu-option" onclick="window.location='editor'"> Edit User </button>
            <button type="button" class="admcp-menu-option" onclick="window.location='settings'"> Website Settings </button>
            <button type="button" class="admcp-menu-option" onclick="window.location='database'"> Database Settings </button>
            <button type="button" class="admcp-menu-option" onclick="window.location='user'"> User Logs </button>
            <button type="button" class="admcp-menu-option" onclick="window.location='activity'"> Login Logs </button>
            <button type="button" class="admcp-menu-option" onclick="window.location='data'"> Product Logs </button>
        </div>
    </div>