<?php
/**
 * Created by PhpStorm.
 * User: ghita
 * Date: 5/26/2018
 * Time: 3:28 PM
 */ ?>

    <div class="admcp-left-bar">
        <div class="admc-left-menu">
            <button type="button" class="admcp-menu-option" onclick="window.location='dashboard'"> Dashboard </button>
            <button type="button" class="admcp-menu-option" onclick="window.location='usermanager'"> Manage Users </button>
            <button type="button" class="admcp-menu-option" onclick="window.location='usereditor'"> Edit User </button>
            <button type="button" class="admcp-menu-option" onclick="window.location='settings'"> Website Settings </button>
            <button type="button" class="admcp-menu-option" onclick="window.location='databaseeditor'"> Database Settings </button>
            <button type="button" class="admcp-menu-option" onclick="window.location='userlogs'"> User Logs </button>
            <button type="button" class="admcp-menu-option" onclick="window.location='loginlogs'"> Login Logs </button>
            <button type="button" class="admcp-menu-option" onclick="window.location='itemlogs'"> Product Logs </button>
        </div>
    </div>