<?php
/**
 * IDE: PhpStorm
 * Project: esser
 * Filename: ${FILE_NAME}
 * User: Gheorghita Mutu
 * Email: gheorghitamutu@gmail.com
 * Date: 4/5/2018
 * Time: 6:14 PM
 */ ?>

</div>

<!-------------------------------------------------footer------------------------------------------------------>

<footer id="footer-container">
    <div class="footer-container-item">
        <a href="#">Policy</a>
    </div>

    <div class="footer-container-item">
        <a href="#">Sitemap</a>
    </div>

    <div class="footer-container-item">
        <a href="#">© 2018 Esser</a>
    </div>
</footer>

</body>
<script src="/resources/js/user-nav-bar.js"></script>

<?php
    if($_SERVER["REQUEST_URI"] === '/user' || $_SERVER["REQUEST_URI"] === '/user/items')
    {
        echo
        "
            <script src=\"/resources/js/user-landing-page.js\"></script>
            <script src=\"/resources/js/items-page.js\"></script>
        ";
    }
?>

</html>