<?php
/**
 * IDE: PhpStorm
 * Project: esser
 * Filename: ${FILE_NAME}
 * User: Gheorghita Mutu
 * Email: gheorghitamutu@gmail.com
 * Date: 4/5/2018
 * Time: 6:14 PM
 */ ?>

<div class="footer">
    <p class="copyright">©2018 The EsserDeveloper Lab, Inc. All rights reserved. </p>
    <div class="data">
        <p id="dataHour"> 10:00 AM</p>
        <p id="dataYear"> 3/19/2018</p>
    </div>

</div>
</div>
</div>

</body>
</html>