<?php
/**
 * IDE: PhpStorm
 * Project: esser
 * Filename: ${FILE_NAME}
 * User: Gheorghita Mutu
 * Email: gheorghitamutu@gmail.com
 * Date: 4/5/2018
 * Time: 6:14 PM
 */ ?>

</div>

<!-------------------------------------------------footer------------------------------------------------------>

<footer id="footer-container">
    <div class="footer-container-item">
        <a href="#">Policy</a>
    </div>

    <div class="footer-container-item">
        <a href="#">Sitemap</a>
    </div>

    <div class="footer-container-item">
        <a href="#">© 2018 Esser</a>
    </div>
</footer>

</body>
<script src="/user-nav-bar.js"></script>
</html>