<?php
/**
 * IDE: PhpStorm
 * Project: esser
 * Filename: header.phtml
 * User: Gheorghita Mutu
 * Email: gheorghitamutu@gmail.com
 * Date: 4/5/2018
 * Time: 6:14 PM
 */
?>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="/resources/css/user/user-nav-bar.css">
        <link rel="stylesheet" type="text/css" href="/resources/css/user/user-landing-page.css">
        <title><?php echo (isset($this->page_title) ? $this->page_title : "Welcome!"); ?></title>
    </head>
<body id="body">

<!------------------------------------------- sidebar trigger   aici am adaugat button admin------------------------------------------------->

<div id="sidebar-trigger-container">
    <div class="sidebar-trigger" id="sidebar-trigger" >
        <div class="top"></div>
        <div class="mid"></div>
        <div class="bottom"></div>
    </div>
    <div id="top-nav-bar-user-landing-page">
        <div id="search-container">
            <form action="" id="search-form">
                <input type="text" placeholder="Search.." name="search" id="search-input">
                <button type="submit" id="search-button"></button>
            </form>
        </div>


        <div id="admin-cp-container-user-landing-page">
            <button type="button" id="admin-cp-button" onclick="redirect('')">Admin</button>
        </div>
    </div>


</div>

<!-------------------------------------------------- sidebar -------------------------------------------------->
<div id="offCanvasSidenav" class="sidenav">
    <div class="sidenav-container-item">
        <div class="sidenav-item-user-icon">
            <img src="/resources/images/user//abstract-user-flat-3.svg">
        </div>

        <div class="sidenav-item">
            <a href="/user">Home</a>
        </div>

        <div class="sidenav-item">
            <a href="/user/alerts">Alerts</a>
        </div>

        <div class="sidenav-item">
            <a href="/user/logs">Logs</a>
        </div>

        <div class="sidenav-item">
            <a href="/user/items">Products</a>
        </div>

        <div class="sidenav-item">
            <a href="/user/users">Groups</a>
        </div>

        <div class="sidenav-item">
            <a href="/user/logout">Logout</a>
        </div>
    </div>
</div>


<!----- Add all page content inside this div if you want the side nav to push page content to the right ------->
<div id="main">