<?php
/**
 * IDE: PhpStorm
 * Project: esser
 * Filename: header.phtml
 * User: Gheorghita Mutu
 * Email: gheorghitamutu@gmail.com
 * Date: 4/5/2018
 * Time: 6:14 PM
 */
?>

<!DOCTYPE html>
<html>
<head>
    <title>User Landing Page</title>
    <meta charset="UTF-8">
    <link href="/assets/normal/css/style_MP.css" rel="stylesheet" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>


<div class="content">

    <div class="header">
        <h1>Esser</h1>
        <p>The best resources planner </p>
    </div>

    <span class="sidenav">
    <a id="nav-username">John Doe</a>
    <a class="nav-button" href="/index.phtml">Home</a>
    <span class="active"><a class="nav-button" href="alerts/view.alerts.html">Alerts</a></span>
    <a class="nav-button" href="logs/view.logs.html">Logs</a>
    <a class="nav-button" href="items/view.items.html">Products</a>
    <a class="nav-button" href="users/view.users.html">Groups</a>
    <a class="nav-button" href="../home/login/login.phtml">Logout</a>
    </span>

    <div class="container">

        <div class="itemsContainer">
            <table id="itemsT">
                <tr>
                    <th>PC spare parts</th>
                    <th>Current cantity</th>
                    <th>Unit</th>

                </tr>
                <tr>
                    <td>Hard</td>
                    <td>50</td>
                    <td>item</td>

                </tr>
                <tr>
                    <td>SSD</td>
                    <td>30</td>
                    <td>item</td>
                </tr>
                <tr>
                    <td>Mother board</td>
                    <td>30</td>
                    <td>item</td>
                </tr>
                <tr>
                    <td>Ram</td>
                    <td>30</td>
                    <td>item</td>
                </tr>

                <tr>
                    <th>Fruits</th>
                    <th>Current cantity</th>
                    <th>Unit</th>
                </tr>
                <tr>
                    <td>Apples</td>
                    <td>20</td>
                    <td>kg</td>
                </tr>

            </table>

        </div>

