<?php
/**
 * IDE: PhpStorm
 * Project: esser
 * Filename: header.phtml
 * User: Gheorghita Mutu
 * Email: gheorghitamutu@gmail.com
 * Date: 4/5/2018
 * Time: 6:14 PM
 */
?>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="/user-nav-bar.css">
        <title><?php echo (isset($this->page_title) ? $this->page_title : "Welcome!"); ?></title>
    </head>
<body id="body">

<!------------------------------------------- sidebar trigger ------------------------------------------------->

<div id="sidebar-trigger-container">
    <div class="sidebar-trigger" id="sidebar-trigger" >
        <div class="top"></div>
        <div class="mid"></div>
        <div class="bottom"></div>
    </div>
    <div id="search-container">
        <form action="" id="search-form">
            <input type="text" placeholder="Search.." name="search" id="search-input">
            <button type="submit" id="search-button"></button>
        </form>
    </div>
</div>

<!-------------------------------------------------- sidebar -------------------------------------------------->
<div id="offCanvasSidenav" class="sidenav">
    <div class="sidenav-container-item">
        <div class="sidenav-item-user-icon">
            <img src="/abstract-user-flat-3.svg">
        </div>

        <div class="sidenav-item">
            <a href="#">Home</a>
        </div>

        <div class="sidenav-item">
            <a href="/alerts">Alerts</a>
        </div>

        <div class="sidenav-item">
            <a href="#">Logs</a>
        </div>

        <div class="sidenav-item">
            <a href="#">Products</a>
        </div>

        <div class="sidenav-item">
            <a href="#">Groups</a>
        </div>

        <div class="sidenav-item">
            <a href="#">Logout</a>
        </div>
    </div>
</div>


<!----- Add all page content inside this div if you want the side nav to push page content to the right ------->
<div id="main">