<?php include VIEW . 'user/header.phtml'; ?>

<div id="main-user-landing-page">

    <div class="container-header-user-landing-page">
        <div class="content-header-user-landing-page">
            <div id="name-header-user-landing-page">
                <div>Esser</div>
            </div>
            <div id="under-title-header-user-landing-page">
                <div>The best resource planner</div>
            </div>
        </div>
    </div>
    <br>
    <div class="notification-container-user-landing-page">
        <div id="notification-container-user-landing-page">
                <button type="button" id="notification-button" onclick="window.location.href = '/user/notifications'">
                    Notifications
                </button>
        </div>
    </div>
    <div class="container-content-user-landing-page">
        <div class="items-container-user-landing-page">
            <div class="container-title-items">
                <div>Products</div>
            </div>
            <div class="items-content-user-landing-page">

                <div class="header-items">
                    <div>Name</div>
                </div>
                <div class="header-items">
                    <div>Group</div>
                </div>
                <div class="header-items">
                    <div>Quantity</div>
                </div><?php
                $array_items=$this->view_data['productsContainer']['items'];
                foreach($array_items as $item){
                    echo"<div class=\"body-items\">";
                    echo "<div>" . $item['itemName'] . "</div>";
                    echo"</div>";

                    echo"<div class=\"body-items\">";
                    echo "<div>" . $item['itemGroup'] . "</div>";
                    echo"</div>";

                    echo"<div class=\"body-items\">";
                    echo "<div>" . $item['itemQuantity'] . "</div>";
                    echo"</div>";
                }
                ?>


            </div>

            <div class="statistics-items-container-user-landing-page">
                <div class="title-statistics-items">
                    <div>Products statistics</div>
                </div>
                <div class="body-statistics-items">


                        <div id="header-row-statistics-items" class="body-statistics-items-element">
                            <div>Total number of products</div>
                        </div>

                        <div  class="body-statistics-items-element">
                            <div><?php echo $this->view_data['productsContainer']['countItems'];?></div>
                        </div>



                        <div id="header-row-statistics-items" class="body-statistics-items-element">
                            <div>Total number of groups</div>
                        </div>

                        <div class="body-statistics-items-element">
                            <div><?php echo $this->view_data['productsContainer']['countItemsGroups'];?></div>
                        </div>


                        <div id="header-row-statistics-items" class="body-statistics-items-element">
                            <div>Average quantity per item</div>
                        </div>

                        <div class="body-statistics-items-element">
                            <div><?php echo round($this->view_data['productsContainer']['avgQuantity'],2);?></div>
                        </div>

                </div>
            </div>

        </div>

        <div class="users-container-user-landing-page">
            <div class="container-title-users">
                <div>Users</div>
            </div>
            <div class="users-content-user-landing-page">
                <div class="header-users">
                    <div>Name</div>
                </div>
                <div class="header-users">
                    <div>Group</div>
                </div>
                <div class="header-users">
                    <div>Email</div>
                </div><?php
                $array_users=$this->view_data['usersContainer']['users'];
                foreach($array_users as $user){
                    echo"<div class=\"body-users\">";
                    echo "<div>" . $user['userName'] . "</div>";
                    echo"</div>";

                    echo"<div class=\"body-users\">";
                    echo "<div>" . $user['userGroup'] . "</div>";
                    echo"</div>";

                    echo"<div class=\"body-users\">";
                    echo "<div>" . $user['userEmail'] . "</div>";
                    echo"</div>";
                }
                ?>
            </div>


            <div class="statistics-users-container-user-landing-page">
                <div class="title-statistics-users">
                    <div>Users statistics</div>
                </div>

                <div class="body-statistics-users">

                    <div id="header-row-statistics-users" class="body-statistics-users-element">
                        <div>Total number of users</div>
                    </div>

                    <div  class="body-statistics-users-element">
                        <div><?php echo $this->view_data['usersContainer']['countUsers']; ?></div>
                    </div>



                    <div id="header-row-statistics-users" class="body-statistics-users-element">
                        <div>Total number of groups</div>
                    </div>

                    <div class="body-statistics-users-element">
                        <div><?php echo $this->view_data['usersContainer']['countGroups']; ?></div>
                    </div>


                    <div id="header-row-statistics-users" class="body-statistics-users-element">
                        <div>Average users per grup</div>
                    </div>

                    <div class="body-statistics-users-element">
                        <div><?php
                            $users=$this->view_data['usersContainer']['countUsers'];
                            $groups=$this->view_data['usersContainer']['countGroups'];
                            if($groups !=0){
                                echo (round($users/$groups,2));
                            }else{
                                echo (0);
                            }
                            ?>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<?php include VIEW . 'user/footer.phtml'; ?>
