<?php include VIEW . 'user/header.phtml'; ?>

<div id="main-user-landing-page">


    <div class="container-header-user-landing-page">
        <div class="content-header-user-landing-page">
            <div id="name-header-user-landing-page">
                <div>Esser</div>
            </div>
            <div id="under-title-header-user-landing-page">
                <div>The best resource planner</div>
            </div>
        </div>
    </div>

    <div class="notification-container-user-landing-page">
        <div id="notification-container-user-landing-page">
                <button type="button" id="notification-button" onclick="redirect('')">Notifications</button>
        </div>
    </div>
    <div class="container-content-user-landing-page">

        <div class="items-container-user-landing-page">
            <div class="container-title-items">
                <div>Products</div>
            </div>
            <div class="items-content-user-landing-page">

                <div class="header-items">
                    <div>Name</div>
                </div>
                <div class="header-items">
                    <div>Group</div>
                </div>
                <div class="header-items">
                    <div>Quantity</div>
                </div>
                <div class="header-items">
                    <div>Stock</div>
                </div>

                <div class="body-items">
                    <div>NumePrenumeMare NumePrenumeFoareMare</div>
                </div>
                <div class="body-items">
                    <div>groupNameFoarteMare</div>
                </div>
                <div class="body-items">
                    <div>quantity</div>
                </div>
                <div class="body-items">
                    <div>20%</div>
                </div>

                <div class="body-items">
                    <div>NumePrenumeMare NumePrenumeFoareMare</div>
                </div>
                <div class="body-items">
                    <div>groupNameFoarteMare</div>
                </div>
                <div class="body-items">
                    <div>quantity</div>
                </div>
                <div class="body-items">
                    <div>20%</div>
                </div>

                <div class="body-items">
                    <div>NumePrenumeMare NumePrenumeFoareMare</div>
                </div>
                <div class="body-items">
                    <div>groupNameFoarteMare</div>
                </div>
                <div class="body-items">
                    <div>quantity</div>
                </div>
                <div class="body-items">
                    <div>20%</div>
                </div>


                <div class="body-items">
                    <div>NumePrenumeMare NumePrenumeFoareMare</div>
                </div>
                <div class="body-items">
                    <div>groupNameFoarteMare</div>
                </div>
                <div class="body-items">
                    <div>quantity</div>
                </div>
                <div class="body-items">
                    <div>20%</div>
                </div>

                <div class="body-items">
                    <div>NumePrenumeMare NumePrenumeFoareMare</div>
                </div>
                <div class="body-items">
                    <div>groupNameFoarteMare</div>
                </div>
                <div class="body-items">
                    <div>quantity</div>
                </div>
                <div class="body-items">
                    <div>20%</div>
                </div>

                <div class="body-items">
                    <div>NumePrenumeMare NumePrenumeFoareMare</div>
                </div>
                <div class="body-items">
                    <div>groupNameFoarteMare</div>
                </div>
                <div class="body-items">
                    <div>quantity</div>
                </div>
                <div class="body-items">
                    <div>20%</div>
                </div>

                <div class="body-items">
                    <div>NumePrenumeMare NumePrenumeFoareMare</div>
                </div>
                <div class="body-items">
                    <div>groupNameFoarteMare</div>
                </div>
                <div class="body-items">
                    <div>quantity</div>
                </div>
                <div class="body-items">
                    <div>20%</div>
                </div>

                <div class="body-items">
                    <div>NumePrenumeMare NumePrenumeFoareMare</div>
                </div>
                <div class="body-items">
                    <div>groupNameFoarteMare</div>
                </div>
                <div class="body-items">
                    <div>quantity</div>
                </div>
                <div class="body-items">
                    <div>20%</div>
                </div>



                <div class="body-items">
                    <div>NumePrenumeMare NumePrenumeFoareMare</div>
                </div>
                <div class="body-items">
                    <div>groupNameFoarteMare</div>
                </div>
                <div class="body-items">
                    <div>quantity</div>
                </div>
                <div class="body-items">
                    <div>20%</div>
                </div>

            </div>

            <div class="statistics-items-container-user-landing-page">
                <div class="title-statistics-items">
                    <div>Products statistics</div>
                </div>
                <div class="body-statistics-items">
                    <div class="row-statistics-items">
                        <div class="header-row-statistics-items">
                            <div>Total number of products</div>
                        </div>
                        <div class="content-row-statistics-items">
                            <div>100</div>
                        </div>
                    </div>

                    <div class="row-statistics-items">
                        <div class="header-row-statistics-items">
                            <div>Total number of groups</div>
                        </div>
                        <div class="content-row-statistics-items">
                            <div>100</div>
                        </div>

                    </div>

                    <div class="row-statistics-items">
                        <div class="header-row-statistics-items">
                            <div>Avg stock content</div>
                        </div>
                        <div class="content-row-statistics-items">
                            <div>100</div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

        <div class="users-container-user-landing-page">
            <div class="container-title-users">
                <div>Users</div>
            </div>
            <div class="users-content-user-landing-page">
                <div class="header-users">
                    <div>Name</div>
                </div>
                <div class="header-users">
                    <div>Group</div>
                </div>
                <div class="header-users">
                    <div>Role</div>
                </div>

                <div class="body-users">
                    <div>NumePeMare NumePrenumeFoare</div>
                </div>
                <div class="body-users">
                    <div>groupNarteMare</div>
                </div>
                <div class="body-users">
                    <div>manager</div>
                </div>

                <div class="body-users">
                    <div>NumePeMare NumePrenumeFoar</div>
                </div>
                <div class="body-users">
                    <div>groupNarteMare</div>
                </div>
                <div class="body-users">
                    <div>normal</div>
                </div>

                <div class="body-users">
                    <div>NumePeMare NumePrenumeFoareMare</div>
                </div>
                <div class="body-users">
                    <div>groupNarteMare</div>
                </div>
                <div class="body-users">
                    <div>manager</div>
                </div>

                <div class="body-users">
                    <div>NumePeMare NumePrenumeFoareMare</div>
                </div>
                <div class="body-users">
                    <div>groupNarteMare</div>
                </div>
                <div class="body-users">
                    <div>manager</div>
                </div>

                <div class="body-users">
                    <div>NumePeMare NumePrenumeFoareMare</div>
                </div>
                <div class="body-users">
                    <div>groupNarteMare</div>
                </div>
                <div class="body-users">
                    <div>manager</div>
                </div>

                <div class="body-users">
                    <div>NumePeMare NumePrenumeFoareMare</div>
                </div>
                <div class="body-users">
                    <div>groupNarteMare</div>
                </div>
                <div class="body-users">
                    <div>manager</div>
                </div>

                <div class="body-users">
                    <div>NumePeMare NumePrenumeFoareMare</div>
                </div>
                <div class="body-users">
                    <div>groupNarteMare</div>
                </div>
                <div class="body-users">
                    <div>manager</div>
                </div>

                <div class="body-users">
                    <div>NumePeMare NMare</div>
                </div>
                <div class="body-users">
                    <div>groupNarteMare</div>
                </div>
                <div class="body-users">
                    <div>manager</div>
                </div>

                <div class="body-users">
                    <div>NumePeMare NumePrenumeFoareMare</div>
                </div>
                <div class="body-users">
                    <div>groupNarteMare</div>
                </div>
                <div class="body-users">
                    <div>manager</div>
                </div>



            </div>

            <div class="statistics-users-container-user-landing-page">
                <div class="title-statistics-users">
                    <div>Users statistics</div>
                </div>

                <div class="body-statistics-users">
                    <div class="row-statistics-users">
                        <div class="header-row-statistics-users">
                            <div>Total number of users</div>
                        </div>
                        <div class="content-row-statistics-users">
                            <div>100</div>
                        </div>
                    </div>

                    <div class="row-statistics-users">
                        <div class="header-row-statistics-users">
                            <div>Total number of admins</div>
                        </div>
                        <div class="content-row-statistics-users">
                            <div>100</div>
                        </div>

                    </div>

                    <div class="row-statistics-users">
                        <div class="header-row-statistics-users">
                            <div>Total number of groups</div>
                        </div>
                        <div class="content-row-statistics-users">
                            <div>100</div>
                        </div>
                    </div>

                    <div class="row-statistics-users">
                        <div class="header-row-statistics-users">
                            <div>Avg enrollment of a user per grup</div>
                        </div>
                        <div class="content-row-statistics-users" id="content-row-statistics-user-last-item">
                            <div>100</div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </div>

</div>
<?php include VIEW . 'user/footer.phtml'; ?>
