<?php include VIEW . 'admincp/header.phtml';?>

<?php include VIEW . 'admincp/menu/header_bar.phtml';?>
    <div class="admcp-tables-body">
        <?php include VIEW . 'admincp/menu/menu.phtml';?>
            <div class="admcp-rt-box">
                <div class="admcp-rt-cnt-box">
                    <div class="admcp-rt-content">
                        <h3 class="adm-rt-title"> Item Groups Editor </h3>
                        <form class="srch-layout" action="/admincp/itemgroupeditor/searchitmgrp" method="POST">
                            <input class="adm-srch-box" required="required" name="searchitmgrp" value="" placeholder="Insert Item Group Name">
                            <button type="submit" class="admcp-srch-btn"> Search </button>
                        </form>
                    </div>
                </div>
                <div class="admcp-rt-result-box">
                    <div class="admcp-rt-content">
                        <h3 class="adm-rt-title"> Item Group Details </h3>
                        <form class="usr-edit-form" method="POST" action="/admincp/itemgroupeditor/editgrouptitle">
                            <div class="ctrl-group" id="grpnamediv">
                                <label id="groupnamelabel"> Current Group Name </label>
                                <?php echo
                                    '<input type="text" name="curitmgrpname" id="cur-itm-grp-name" value="' .
                                    (isset($this->view_data['itmgroup']['iGroupName'])?
                                        $this->view_data['itmgroup']['iGroupName']: "") . '" disabled>'; ?>
                                <label id="groupnamelabel"> Insert a new name for the group here: </label>
                                <input type="text" name="newgrpname" id="grp-name" required="required"
                                       value="" placeholder="Input New Group Name">
                            </div>
                            <button type="submit" class="admcp-save-btn" name="edititmgrpnameid"
                                    value="<?php echo
                                    ((isset($this->view_data['itmgroup']['iGroupId']))?
                                        $this->view_data['itmgroup']['iGroupId']:''); ?>"> Save </button>
                        </form>
                        <form class="usr-edit-form" method="POST" action="/admincp/itemgroupeditor/editgroupdescription">
                            <div class="ctrl-group" id="grpdscrptdiv">
                                <label id="groupdescrptionlabel"> Group Description </label>
                                <textarea name="curitmgrpname" id="cur-grp-descrp" disabled
                                          minlength="6" maxlength="2000" rows="5" cols="10"><?php echo
                                    (isset($this->view_data['itmgroup']['iGroupDescription']))?
                                        $this->view_data['itmgroup']['iGroupDescription']: ""; ?></textarea>
                                <br />
                                <textarea name="newitmgrpdescrp" id="grp-descrp" minlength="6" maxlength="2000" rows="5" cols="10"
                                          placeholder="Input here new item group description..."></textarea>
                            </div>
                            <button type="submit" class="admcp-save-btn" name="edititmgrpdscrpid"
                                    value="<?php echo
                                    ((isset($this->view_data['itmgroup']['iGroupId']))?
                                        $this->view_data['itmgroup']['iGroupId']:''); ?>"> Save </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

<?php include VIEW . 'admincp/footer.phtml';?>