<?php
/**
 * Created by PhpStorm.
 * User: ghita
 * Date: 5/26/2018
 * Time: 3:56 PM
 */ ?>

<?php include VIEW . 'admincp/header.phtml';?>

<?php include VIEW . 'admincp/menu/header_bar.phtml';?>

<div class="admcp-tables-body">
    <?php include VIEW . 'admincp/menu/menu.phtml';?>
    <div class="admcp-rt-box">
        <div class="admcp-rt-cnt-box">
            <div class="admcp-rt-content">
            </div>
        </div>
    </div>
</div>

<?php include VIEW . 'admincp/footer.phtml';?>