<?php include VIEW . 'admincp/header.phtml';?>

<?php include VIEW . 'admincp/menu/header_bar.phtml';?>

    <div class="admcp-tables-body">

        <?php include VIEW . 'admincp/menu/menu.phtml';?>
        <div class="admcp-rt-box">
            <div class="admcp-rt-cnt-box">
                <div class="admcp-rt-content">
                    <h3 class="adm-rt-title"> Item Group Management </h3>
                    <div class="flex-table">
                        <h2 class="adm-rt-title"> Item Groups </h2>
                        <div class="flex-table-head">
                            <div class="flex-table-row">
                                <div class="flex-table-th"> Group Name </div>
                                <div class="flex-table-th"> Owned By </div>
                                <div class="flex-table-th"> Description </div>
                                <div class="flex-table-th"> Number Items </div>
                                <div class="flex-table-th"> Total Products </div>
                                <div class="flex-table-th"> Creation Date </div>
                                <div class="flex-table-th"> Edit </div>
                                <div class="flex-table-th"> Delete </div>
                            </div>
                        </div>
                        <div class="flex-table-body">
                            <?php
                            for ($i = 0; $i < count($this->view_data['grouplist']); ++$i) {
                                echo
                                    "<div class=\"flex-table-row\">". PHP_EOL .
                                    "<div class=\"flex-table-td\">". $this->view_data['grouplist'][$i]['iGroupName']. "</div>" . PHP_EOL .
                                    "<div class=\"flex-table-td\">". $this->view_data['grouplist'][$i]['owner'] ."</div>" . PHP_EOL .
                                    "<div class=\"flex-table-td\">" .$this->view_data['grouplist'][$i]['iGroupDescription'] . "</div>" . PHP_EOL .
                                    "<div class=\"flex-table-td\">" .$this->view_data['grouplist'][$i]['nrofitems'] . "</div>" . PHP_EOL .
                                    "<div class=\"flex-table-td\">" .$this->view_data['grouplist'][$i]['totalproducts'] . "</div>" . PHP_EOL .
                                    "<div class=\"flex-table-td\">" .$this->view_data['grouplist'][$i]['iGroupCreatedAt'] . "</div>" . PHP_EOL .
                                    "<div class=\"flex-table-td\">" . PHP_EOL .
                                    "<form action=\"/admincp/itemgroupeditor/getitmgroup\" method=\"POST\">" . PHP_EOL .
                                    "<button type=\"submit\" class=\"admcp-srch-btn\" name=\"edititemgroup\" 
                                        value=\"".$this->view_data['grouplist'][$i]['iGroupId']."\"> Edit </button>" . PHP_EOL .
                                    "</form>" . PHP_EOL .
                                    "</div>".PHP_EOL .
                                    "<div class=\"flex-table-td\">" . PHP_EOL .
                                    "<form action=\"/admincp/itemgroups/delitemgroup\" method=\"POST\">" . PHP_EOL .
                                    "<button type=\"submit\" class=\"admcp-srch-btn\" name=\"delitemgroup\" 
                                        value=\"".$this->view_data['grouplist'][$i]['iGroupId']."\"> Delete </button>" . PHP_EOL .
                                    "</form>" . PHP_EOL .
                                    "</div>" . PHP_EOL .
                                    "</div>";
                            }?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php include VIEW . 'admincp/footer.phtml';?>