<?php include VIEW . 'admincp/header.phtml';?>

<?php include VIEW . 'admincp/menu/header_bar.phtml';?>

<div class="admcp-tables-body">

    <?php include VIEW . 'admincp/menu/menu.phtml';?>
            <div class="admcp-rt-box">
                <div class="admcp-rt-cnt-box">
                    <div class="admcp-rt-content">
                        <h3 class="adm-rt-title"> Search a user group </h3>
                        <form class="srch-layout" action="/admincp/usergroupeditor/searchusergroup" method="POST">
                            <input class="adm-srch-box" required="required" name="searchusergroup" value="" placeholder="Insert User Account">
                            <button type="submit" class="admcp-srch-btn"> Search </button>
                        </form>
                    </div>
                </div>
                <div class="admcp-rt-cnt-box">
                    <div class="admcp-rt-content">
                        <h3 class="adm-rt-title"> Members Management </h3>
                        <div class="flex-table">
                            <h2 class="adm-rt-title"> Members List </h2>
                            <div class="flex-table-head">
                                <div class="flex-table-row">
                                    <div class="flex-table-th"> Member Name </div>
                                    <div class="flex-table-th"> Joined Date </div>
                                    <div class="flex-table-th"> General Info </div>
                                    <div class="flex-table-th"> Edit </div>
                                    <div class="flex-table-th"> Delete </div>
                                </div>
                            </div>
                            <div class="flex-table-body">
                            <?php
                            for ($i = 0; $i < count($this->view_data['memberlist']); ++$i) {
                            echo
                                "<div class=\"flex-table-row\">" . PHP_EOL
                                . "<div class=\"flex-table-td\">" .
                                $this->view_data['memberlist'][$i]['userName']
                                . "</div>" . PHP_EOL
                                . "<div class=\"flex-table-td\">" .
                                $this->view_data['memberlist'][$i]['grpRelCreatedAt']
                                . "</div>" . PHP_EOL
                                . "<div class=\"flex-table-td\">" .
                                "Group Manager: <label class=\"info-status\">" .
                                $this->view_data['memberlist'][$i]['canMngMbs'] .
                                "</label> | Can Manage Items: <label class=\"info-status\"> " .
                                $this->view_data['memberlist'][$i]['canUpdItm'] .
                                "</label> | " .
                                $this->view_data['memberlist'][$i]['userEmail'] .
                                "</label>  | <label class=\"" .
                                $this->view_data['memberlist'][$i]['labelType'] .
                                "\">" . $this->view_data['memberlist'][$i]['userState']
                                . "</div>" . PHP_EOL
                                . "<div class=\"flex-table-td\">" .
                                "<form action=\"/admincp/usereditor/getuser\" method=\"POST\">" .
                                "<button type=\"submit\" class=\"admcp-srch-btn\" name=\"edituser\" 
                                    value=\"" . $this->view_data['memberlist'][$i]['userId'] . "\">" .
                                " Edit </button></form></div>" . PHP_EOL
                                . "<div class=\"flex-table-td\">" .
                                "<form action=\"/admincp/usergroupeditor/removefromgroup\" method=\"POST\">" .
                                "<button type=\"submit\" class=\"admcp-srch-btn\" name=\"remfromgrp\" value=\"" .
                                    $this->view_data['memberlist'][$i]['userId'].'/'.$this->view_data['generalgroupinfo']['groupid'] . "\">" .
                                " Remove </button></form></div>" . PHP_EOL
                                . "</div>";
                            }?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="admcp-rt-result-box">
                    <div class="admcp-rt-content">
                        <h3 class="adm-rt-title"> User Group Details </h3>
                        <form class="usr-edit-form" method="POST" action="/admincp/usergroupeditor/editgrouptitle">
                            <div class="ctrl-group" id="grpnamediv">
                                <label id="groupnamelabel"> Current Group Name </label>
                                <?php echo
                                '<input type="text" name="curgrpname" id="cur-grp-name" value="' .
                                     (isset($this->view_data['generalgroupinfo']['groupname'])?
                                         $this->view_data['generalgroupinfo']['groupname']: "") . '" disabled>'; ?>
                                <label id="groupnamelabel"> Insert a new name for the group here: </label>
                                <input type="text" name="newgrpname" id="grp-name" required="required"
                                       value="" placeholder="Input New Group Name">
                            </div>
                            <button type="submit" class="admcp-save-btn" name="editgrouptitleid"
                                    value="<?php echo
                                    ((isset($this->view_data['generalgroupinfo']['groupid']))?
                                        $this->view_data['generalgroupinfo']['groupid']:''); ?>"> Save </button>
                        </form>
                        <form class="usr-edit-form" method="POST" action="/admincp/usergroupeditor/editgroupdescription">
                            <div class="ctrl-group" id="grpdscrptdiv">
                                <label id="groupdescrptionlabel"> Group Description </label>
                                <textarea name="curgrpname" id="cur-grp-descrp" disabled
                                          minlength="6" maxlength="2000" rows="5" cols="10"><?php echo
                                    (isset($this->view_data['generalgroupinfo']['groupdscrp']))?
                                        $this->view_data['generalgroupinfo']['groupdscrp']: ""; ?></textarea>
                                <br />
                                <textarea name="newgrpdescrp" id="grp-descrp" minlength="6" maxlength="2000" rows="5" cols="10"
                                          placeholder="Input here new user group description..."></textarea>
                            </div>
                            <button type="submit" class="admcp-save-btn" name="editgroupdscrpid"
                                    value="<?php echo
                                    ((isset($this->view_data['generalgroupinfo']['groupid']))?
                                        $this->view_data['generalgroupinfo']['groupid']:''); ?>"> Save </button>
                        </form>
                    </div>
                </div>
            </div>            
        </div>

<?php include VIEW . 'admincp/footer.phtml';?>