<?php include VIEW . 'user/header.phtml';?>

<div id="main-first-row-container">
    <div id="page-title">
        <p>Notifications</p>
    </div>
</div>

<div id="main-second-row-container">
    <div class="container-row">
        <div class="date">
            <p>28-02-2018 19:00:01</p>
        </div>

        <div class="message">
            <p>22 <span class="neutral">Coffee bags</span> were taken by Office 5 !
                <span class="warning">0 Coffee bags left!</span></p>
        </div>
    </div>

    <div class="container-row">
        <div class="date">
            <p>28-02-2018 19:00:01</p>
        </div>

        <div class="message">
            <p>22 <span class="neutral">Coffee bags</span> were taken by Office 5 !
                <span class="warning">0 Coffee bags left!</span></p>
        </div>
    </div>

    <div class="container-row">
        <div class="date">
            <p>28-02-2018 19:00:01</p>
        </div>

        <div class="message">
            <p>22 <span class="neutral">Coffee bags</span> were taken by Office 5 !
                <span class="warning">0 Coffee bags left!</span></p>
        </div>
    </div>

    <div class="container-row">
        <div class="date">
            <p>28-02-2018 19:00:01</p>
        </div>

        <div class="message">
            <p>22 <span class="neutral">Coffee bags</span> were taken by Office 5 !
                <span class="warning">0 Coffee bags left!</span></p>
        </div>
    </div>

    <div class="container-row">
        <div class="date">
            <p>28-02-2018 19:00:01</p>
        </div>

        <div class="message">
            <p>22 <span class="neutral">Coffee bags</span> were taken by Office 5 !
                <span class="warning">0 Coffee bags left!</span></p>
        </div>
    </div>

    <div class="container-row">
        <div class="date">
            <p>28-02-2018 19:00:01</p>
        </div>

        <div class="message">
            <p>22 <span class="neutral">Coffee bags</span> were taken by Office 5 !
                <span class="warning">0 Coffee bags left!</span></p>
        </div>
    </div>

    <div class="container-row">
        <div class="date">
            <p>28-02-2018 19:00:01</p>
        </div>

        <div class="message">
            <p>22 <span class="neutral">Coffee bags</span> were taken by Office 5 !
                <span class="warning">0 Coffee bags left!</span></p>
        </div>
    </div>

    <div class="container-row">
        <div class="date">
            <p>28-02-2018 19:00:01</p>
        </div>

        <div class="message">
            <p>22 <span class="neutral">Coffee bags</span> were taken by Office 5 !
                <span class="warning">0 Coffee bags left!</span></p>
        </div>
    </div>

    <div class="container-row">
        <div class="date">
            <p>28-02-2018 19:00:01</p>
        </div>

        <div class="message">
            <p>22 <span class="neutral">Coffee bags</span> were taken by Office 5 !
                <span class="warning">0 Coffee bags left!</span></p>
        </div>
    </div>

    <div class="container-row">
        <div class="date">
            <p>28-02-2018 19:00:01</p>
        </div>

        <div class="message">
            <p>22 <span class="neutral">Coffee bags</span> were taken by Office 5 !
                <span class="warning">0 Coffee bags left!</span></p>
        </div>
    </div>

    <div class="container-row">
        <div class="date">
            <p>28-02-2018 19:00:01</p>
        </div>

        <div class="message">
            <p>22 <span class="neutral">Coffee bags</span> were taken by Office 5 !
                <span class="warning">0 Coffee bags left!</span></p>
        </div>
    </div>

    <div class="container-row">
        <div class="date">
            <p>28-02-2018 19:00:01</p>
        </div>

        <div class="message">
            <p>22 <span class="neutral">Coffee bags</span> were taken by Office 5 !
                <span class="warning">0 Coffee bags left!</span></p>
        </div>
    </div>

    <div class="container-row">
        <div class="date">
            <p>28-02-2018 19:00:01</p>
        </div>

        <div class="message">
            <p>22 <span class="neutral">Coffee bags</span> were taken by Office 5 !
                <span class="warning">0 Coffee bags left!</span></p>
        </div>
    </div>

</div>

<?php include VIEW . 'user/footer.phtml';?>