<?php include VIEW . 'user/header.phtml';?>

<div id="main-first-row-container">
    <div id="page-title">
        <h1>Notifications</h1>
    </div>
</div>

<div id="main-second-row-container">
    <div class="container">
    <?php

    if (empty($this->view_data["notifications"]))
    {
        echo
        '<div class="container-row">    
                <div class="message">
                    <p>There are no new notifications!</p>
                </div>
            </div>';

    }
    else
    {
        foreach ($this->view_data["notifications"] as $notification)
        {
            echo
            '<div class="container-row">
            <div class="date">
                <p>'. $notification["ntfCreatedAt"] . '</p>
            </div>
    
            <div class="message">
                <p>' . $notification["item_name"] . ' ' . $notification["ntfDscrp"] . '</p>
            </div>
            </div>';
        }
    }
    ?>
    </div>

</div>

<?php include VIEW . 'user/footer.phtml';?>