<?php
/**
 * Created by PhpStorm.
 * User: ghita
 * Date: 5/26/2018
 * Time: 3:56 PM
 */ ?>

<?php include VIEW . 'admincp/header.phtml';?>

<?php include VIEW . 'admincp/menu/header_bar.phtml';?>

<div class="admcp-tables-body">
    <?php include VIEW . 'admincp/menu/menu.phtml';?>
    <div class="admcp-rt-box">
        <div class="admcp-rt-cnt-box">
            <div class="admcp-rt-content">
                <h3 class="adm-rt-title"> Change Esser Title </h3>
                <form type="POST" class="usr-edit-form">
                    <fieldset>
                        <legend></legend>
                        <div class="ctrl-group">
                            <label> Old Esser Title </label> <input type="text" name="OldEsserTitle" id="old-esser-name" value="Esser" disabled>
                        </div>
                        <div class="ctrl-group">
                            <label> Input New Title </label> <input type="text" name="NewEsserTitle" id="new-esser-name" value="">
                        </div>
                    </fieldset>
                    <div class="ctrl-group">
                        <button type="button" class="admcp-save-btn" onclick="changeEsserTitle('new-esser-name')"> Save </button>
                        <button type="button" class="admcp-save-btn" onclick="window.location='dashboard'"> Cancel </button>
                    </div>
                </form>
                <h3 class="adm-rt-title"> Change Root AdminCP User </h3>
                <form type="POST" class="usr-edit-form">
                    <fieldset>
                        <legend></legend>
                        <div class="ctrl-group">
                            <label> Old Root User </label> <input type="text" name="OldRootUser" id="old-root-name" value="Edward" disabled>
                        </div>
                        <div class="ctrl-group">
                            <label> Input New User </label> <input type="text" name="NewRootUser" id="new-root-name" value="">
                        </div>
                    </fieldset>
                    <div class="ctrl-group">
                        <button type="button" class="admcp-save-btn" onclick="changeRootUser('new-root-name')"> Save </button>
                        <button type="button" class="admcp-save-btn" onclick="window.location='dashboard'"> Cancel </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<?php include VIEW . 'admincp/footer.phtml';?>