<?php
/**
 * Created by PhpStorm.
 * User: ghita
 * Date: 5/26/2018
 * Time: 3:56 PM
 */ ?>

<?php include VIEW . 'admincp/header.phtml';?>

<?php include VIEW . 'admincp/menu/header_bar.phtml';?>

<div class="admcp-tables-body">
    <?php include VIEW . 'admincp/menu/menu.phtml';?>
    <div class="admcp-rt-box">
        <div class="admcp-rt-cnt-box">
            <div class="admcp-rt-content">
                <h3 class="adm-rt-title"> Change Esser Title </h3>
                <form class="usr-edit-form" method="POST" action="settings/changetitle" >
                    <fieldset>
                        <legend></legend>
                        <div class="ctrl-group">
                            <label> Old Esser Title </label> <input title="CurrentTitle" type="text" name="oldtitle" id="old-esser-name" value="<?php echo $this->view_data['currenttitle']; ?>" disabled>
                        </div>
                        <div class="ctrl-group">
                            <label> Input New Title </label> <input title="NewTitle"  required="required" type="text" name="newtitle" id="new-esser-name" value="">
                        </div>
                        <div class="ctrl-group">
                            <button type="submit" class="admcp-save-btn"> Save </button>
                            <button type="button" class="admcp-save-btn" onclick="window.location='dashboard'"> Cancel </button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>

<?php include VIEW . 'admincp/footer.phtml';?>