<?php include VIEW . 'user/header.phtml';?>
    
    <!-- Register a new group Form -->
    
    <div class="modal" id="groupForm">
        <div class="groupFormContent">
            <div class="Title">Add a new group</div>
            <form>
            <div class="formElement">Name:</div>
            <input type="text" name="newGroupName" value="NewGroup" class="formElement"><br>
            </form>
            <a href="#">
                <button class="closeButton FormButton">Add Group</button>
            </a>
            <a href="#">
                <button class="closeButton FormButton">Cancel</button>
            </a>
        </div>
    </div>
    
    <!-- Register a new product Form -->
    
    <div class="modal" id="productForm">
        <div class="productFormContent">
            <div class="Title">Add a new group</div>
            <form>
            <div class="formElement">Name:</div>
            <input type="text" name="newProductName" value="NewProduct" class="formElement"><br>
            <div class="formElement">Quantity:</div>
            <input type="text" name="newProductQuantity" value="NewProductQ" class="formElement"><br>
            <div class="formElement">Tile Image:</div>
            <button class="FormButton">Browse</button>
            </form>
            <a href="#">
                <button class="FormButton closeButton ">Add Product</button>
            </a>
            <a href="#">
                <button class="FormButton closeButton ">Cancel</button>
            </a>
        </div>
    </div>
    <link rel="stylesheet" type="text/css" href="/resources/css/user/pmc_groups_of_items_style.css">
    <body>
        <!-- Section to be shown -->
        
        <div class="ProductGroups">
            <div class="Title">Product Groups</div>
            <div class="Menu">
                <a href="#groupForm"><button class="MenuButton" id="addGroup">Add Group</button>
                </a>
                <button class="MenuButton" id="deleteGroup">Delete Group</button>
            </div>
            <div class="ProductGroup">
                <a href="#productForm"><div class="GroupButton">Add Product</div></a>
                <a href="#hide1" id="hide1">
                    <div class="GroupName">+ PC Parts</div>
                </a>
                <a href="#" id="show1">
                    <div class="GroupName">- PC Parts</div>
                </a>
                <div id="Contents1">
                    <div class="Product">
                        <img class="ProductIcon" src="/resources/images/user/cpu.png" alt="CPU">
                        <div class="ProductName">CPU</div>
                        <div class="ProductQuantity">12</div>
                        <div class="ProductAvailable">Yes</div>
                        <button class="ProductButton">Remove Item</button>
                        <button class="ProductButton">Add Quantity</button>
                        <button class="ProductButton">Remove Quantity</button>
                        <button class="ProductButton">Request Quantity</button>
                    </div>
                    <div class="Product">
                        <img class="ProductIcon" src="/resources/images/user/hdd.png" alt="HDD">
                        <div class="ProductName">HDD</div>
                        <div class="ProductQuantity">12</div>
                        <div class="ProductAvailable">Yes</div>
                        <button class="ProductButton">Remove Item</button>
                        <button class="ProductButton">Add Quantity</button>
                        <button class="ProductButton">Remove Quantity</button>
                        <button class="ProductButton">Request Quantity</button>
                    </div>
                    <div class="Product">
                        <img class="ProductIcon" src="/resources/images/user/motherboard.png" alt="Motherboard">
                        <div class="ProductName">Motherboard</div>
                        <div class="ProductQuantity">12</div>
                        <div class="ProductAvailable">Yes</div>
                        <button class="ProductButton">Remove Item</button>
                        <button class="ProductButton">Add Quantity</button>
                        <button class="ProductButton">Remove Quantity</button>
                        <button class="ProductButton">Request Quantity</button>
                    </div>
                    <div class="Product">
                        <img class="ProductIcon" src="/resources/images/user/gpu.png" alt="GPU">
                        <div class="ProductName">GPU</div>
                        <div class="ProductQuantity">12</div>
                        <div class="ProductAvailable">Yes</div>
                        <button class="ProductButton">Remove Item</button>
                        <button class="ProductButton">Add Quantity</button>
                        <button class="ProductButton">Remove Quantity</button>
                        <button class="ProductButton">Request Quantity</button>
                    </div>
                    <div class="Product">
                        <img class="ProductIcon" src="/resources/images/user/ssd.png" alt="SSD">
                        <div class="ProductName">SSD</div>
                        <div class="ProductQuantity">12</div>
                        <div class="ProductAvailable">Yes</div>
                        <button class="ProductButton">Remove Item</button>
                        <button class="ProductButton">Add Quantity</button>
                        <button class="ProductButton">Remove Quantity</button>
                        <button class="ProductButton">Request Quantity</button>
                    </div>
                    <div class="Product">
                        <img class="ProductIcon" src="/resources/images/user/Case.png" alt="Case">
                        <div class="ProductName">Case</div>
                        <div class="ProductQuantity">12</div>
                        <div class="ProductAvailable">Yes</div>
                        <button class="ProductButton">Remove Item</button>
                        <button class="ProductButton">Add Quantity</button>
                        <button class="ProductButton">Remove Quantity</button>
                        <button class="ProductButton">Request Quantity</button>
                    </div>
                    <div class="Product">
                        <img class="ProductIcon" src="/resources/images/user/psu.png" alt="PSU">
                        <div class="ProductName">PSU</div>
                        <div class="ProductQuantity">12</div>
                        <div class="ProductAvailable">Yes</div>
                        <button class="ProductButton">Remove Item</button>
                        <button class="ProductButton">Add Quantity</button>
                        <button class="ProductButton">Remove Quantity</button>
                        <button class="ProductButton">Request Quantity</button>
                    </div>
                    <div class="Product">
                        <img class="ProductIcon" src="/resources/images/user/cooler.png" alt="Cooler">
                        <div class="ProductName">Cooler</div>
                        <div class="ProductQuantity">12</div>
                        <div class="ProductAvailable">Yes</div>
                        <button class="ProductButton">Remove Item</button>
                        <button class="ProductButton">Add Quantity</button>
                        <button class="ProductButton">Remove Quantity</button>
                        <button class="ProductButton">Request Quantity</button>
                    </div>
                </div>
            </div>
            <div class="ProductGroup">
                <a href="#productForm"><div class="GroupButton">Add Product</div></a>
                <a href="#hide2" id="hide2">
                    <div class="GroupName">+ Fruits</div>
                </a>
                <a href="#" id="show2">
                    <div class="GroupName">- Fruits</div>
                </a>
                <div id="Contents2">
                    <div class="Product">
                        <img class="ProductIcon" src="/resources/images/user/default.png" alt="Bananas">
                        <div class="ProductName">Bananas</div>
                        <div class="ProductQuantity">12</div>
                        <div class="ProductAvailable">Yes</div>
                        <button class="ProductButton">Remove Item</button>
                        <button class="ProductButton">Add Quantity</button>
                        <button class="ProductButton">Remove Quantity</button>
                        <button class="ProductButton">Request Quantity</button>
                    </div>
                    <div class="Product">
                        <img class="ProductIcon" src="/resources/images/user/default.png" alt="Apples">
                        <div class="ProductName">Apples</div>
                        <div class="ProductQuantity">12</div>
                        <div class="ProductAvailable">Yes</div>
                        <button class="ProductButton">Remove Item</button>
                        <button class="ProductButton">Add Quantity</button>
                        <button class="ProductButton">Remove Quantity</button>
                        <button class="ProductButton">Request Quantity</button>
                    </div>
                </div>
            </div>
        </div>

<?php include VIEW . 'user/footer.phtml';?>