<?php include VIEW . 'user/header.phtml';?>

    <div id="main-container-items-page">
        <div id="left-container-group"><?php
            if($this->view_data['permissionModifyItemsGroup'] == "1"){
                echo "<div id=\"post-group\">";
                echo"<button type=\"button\" id=\"post-group-button\" onclick=\"postGroupFunction()\">";
                echo"Add Group";
                echo"</\"button\">";
                echo"</div>";

                echo"<div id=\"delete-group\">";
                echo"<button type=\"button\" id=\"delete-group-button\" onclick=\"deleteGroupFunction()\">";
                echo"Delete Group";
                echo"</button>";
                echo"</div>";
                }
             ?>
            <div id="get-group">
                <button type="button" id="get-group-button" onclick="getGroupFunction()">
                  List Groups
                </button>
            </div>

        </div>

        <div id="right-container-group">

            <div id="container-post-group">
                <form class="post-item-form" method="POST">
                    <a class="main-text"> Group Name </a>
                    <input class="fill-box" type="text" name="gName" value="" placeholder="Enter group name" required="required"/>
                    <p class="main-text"> Group Description </p>
                    <input class="fill-box" type="text" name="gDescription" value="" placeholder="Enter group description" required="required"/>
                    <input type="submit" class="submit-button-post-group" value="Submit">
                </form>
            </div>

            <div id="container-delete-group"><?php
                $groups=$this->view_data['groupOfItems'];

                echo "<div class=\"header-element-group\">";
                echo "<div>Group Name</div>";
                echo "</div>";

                echo "<div class=\"header-element-group\">";
                echo "<div>Owner Name</div>";
                echo "</div>";

                echo "<div class=\"header-element-group\">";
                echo "<div>Group Description</div>";
                echo "</div>";

                echo "<div class=\"header-element-group\">";
                echo "<div>Created Date </div>";
                echo "</div>";

                echo "<div class=\"header-element-group\">";
                echo "<div>Updated Date</div>";
                echo "</div>";

                echo "<div class=\"header-element-group\ id=\"element-to-hide\">";
                echo "<div> </div>";
                echo "</div>";

                foreach($groups as $group){
                    echo "<div class=\"body-element-group\">";
                    echo "<div>". $group['iGroupName']."</div>";
                    echo "</div>";

                    echo "<div class=\"body-element-group\">";
                    echo "<div>". $group['uGroupName']."</div>";
                    echo "</div>";

                    echo "<div class=\"body-element-group\">";
                    echo "<div>". $group[ 'iGroupDescription']."</div>";
                    echo "</div>";

                    echo "<div class=\"body-element-group\">";
                    echo "<div>". $group['iGroupCreatedAt']."</div>";
                    echo "</div>";

                    echo "<div class=\"body-element-group\">";
                    echo "<div>". $group['iGroupUpdatedAt']."</div>";
                    echo "</div>";


                    echo"<form class=\"post-item-form\" method=\"POST\">";
                    echo "<input  class=\"del-button\" name=\"delButton\" value=\"".$group['iGroupName']."\" required=\"required\"/>";
                    echo "<input  class=\"del-button\" name=\"delButtonUserGroupId\" value=\"".$group['uGroupId']."\" required=\"required\"/>";
                    echo "<input type=\"submit\" class=\"delete-button\" class=\"submit-button-delete-group\" value=\"X\">";
                    echo"</form>";
                }
                ?>

            </div>

            <div id="container-get-group"><?php
                $groups=$this->view_data['groupOfItems'];

                echo "<div class=\"header-element-group\">";
                echo "<div>Group Name</div>";
                echo "</div>";

                echo "<div class=\"header-element-group\">";
                echo "<div>Owner Name</div>";
                echo "</div>";

                echo "<div class=\"header-element-group\">";
                echo "<div>Group Description</div>";
                echo "</div>";

                echo "<div class=\"header-element-group\">";
                echo "<div>Created Date </div>";
                echo "</div>";

                echo "<div class=\"header-element-group\">";
                echo "<div>Updated Date</div>";
                echo "</div>";

                foreach($groups as $group){
                    echo "<div class=\"body-element-group\">";
                    echo "<div>". $group['iGroupName']."</div>";
                    echo "</div>";

                    echo "<div class=\"body-element-group\">";
                    echo "<div>". $group['uGroupName']."</div>";
                    echo "</div>";

                    echo "<div class=\"body-element-group\">";
                    echo "<div>". $group[ 'iGroupDescription']."</div>";
                    echo "</div>";

                    echo "<div class=\"body-element-group\">";
                    echo "<div>". $group['iGroupCreatedAt']."</div>";
                    echo "</div>";

                    echo "<div class=\"body-element-group\">";
                    echo "<div>". $group['iGroupUpdatedAt']."</div>";
                    echo "</div>";


                }
                    ?>
            </div>


        </div>

    </div>

<?php include VIEW . 'user/footer.phtml';?>