<?php include VIEW . 'user/header.phtml';?>

    <div id="main-container-items-page">
        <div id="left-container-group">
            <div id="post-group">
                <button type="button" id="post-group-button" onclick= "postGroupFunction()">
                    Add Group
                </button>
            </div>

            <div id="delete-group">
                <button type="button" id="delete-group-button" onclick="deleteGroupFunction()">
                    Delete Group
                </button>
            </div>

            <div id="get-group">
                <button type="button" id="get-group-button" onclick="getGroupFunction()">
                    List Group
                </button>
            </div>

        </div>

        <div id="right-container-group">

            <div id="container-post-group">
                <form class="post-item-form" method="POST">
                    <a class="main-text"> Group Name </a>
                    <input class="fill-box" type="text" name="gName" value="" placeholder="Enter group name" required="required"/>
                    <p class="main-text"> Group Description </p>
                    <input class="fill-box" type="text" name="gDescription" value="" placeholder="Enter group description" required="required"/>
                    <input type="submit" class="submit-button-post-group" value="Submit">

                </form>
            </div>

            <div id="container-delete-group">
                va fi delete item
            </div>

            <div id="container-get-group">
                get items
            </div>


        </div>

    </div>

<?php include VIEW . 'user/footer.phtml';?>