CREATE OR REPLACE TRIGGER trg_add_to_nrm_usr AFTER INSERT ON USERACCS FOR EACH ROW
  BEGIN
    IF (:NEW.USERID = 1) THEN
      null;
    ELSE
      INSERT INTO GROUPRELATIONS (USERID, UGROUPID, CANUPDITM, CANMNGMBS) VALUES (:NEW.USERID, 3, 0, 0);
    end if;
  end;
/