ALTER TABLE GROUPRELATIONS DROP CONSTRAINT FK_RUSERID;
ALTER TABLE GROUPRELATIONS DROP CONSTRAINT fk_rGroupId;
ALTER TABLE GROUPRELATIONS ADD CONSTRAINT fk_rUserId FOREIGN KEY(userId) REFERENCES USERACCS(userId) ON DELETE CASCADE;
ALTER TABLE GROUPRELATIONS ADD CONSTRAINT fk_rGroupId FOREIGN KEY(uGroupId) REFERENCES USERGROUPS(uGroupId) ON DELETE CASCADE;

ALTER TABLE ITEMGROUPOWNERSHIPS DROP CONSTRAINT fk_igownedId;
ALTER TABLE ITEMGROUPOWNERSHIPS DROP CONSTRAINT fk_igownerId;
ALTER TABLE ITEMGROUPOWNERSHIPS ADD CONSTRAINT fk_igownerId FOREIGN KEY (igOwnerId) REFERENCES USERGROUPS(uGroupId) ON DELETE CASCADE;
ALTER TABLE ITEMGROUPOWNERSHIPS ADD CONSTRAINT fk_igownedId FOREIGN KEY (igId) REFERENCES ITEMGROUPS(iGroupId) ON DELETE CASCADE;

ALTER TABLE ITEMS DROP CONSTRAINT fk_igroupId;
ALTER TABLE ITEMS ADD CONSTRAINT fk_igroupId FOREIGN KEY (iGroupId) REFERENCES ITEMGROUPS(iGroupId) ON DELETE CASCADE;

ALTER TABLE NOTIFICATIONS DROP CONSTRAINT fk_nItemId;
ALTER TABLE NOTIFICATIONS ADD CONSTRAINT fk_nItemId  FOREIGN KEY (nItemId) REFERENCES ITEMS (itemId) ON DELETE CASCADE;

ALTER TABLE UGRPNTFRELATIONS DROP CONSTRAINT fk_usrgnNotifiedGroupId;
ALTER TABLE UGRPNTFRELATIONS DROP CONSTRAINT fk_usrgnNotificationId;
ALTER TABLE UGRPNTFRELATIONS ADD CONSTRAINT fk_usrgnNotifiedGroupId FOREIGN KEY (usrgnNotifiedGroupId) REFERENCES USERGROUPS (uGroupId) ON DELETE CASCADE;
ALTER TABLE UGRPNTFRELATIONS ADD CONSTRAINT fk_usrgnNotificationId  FOREIGN KEY (usrgnNotificationId) REFERENCES NOTIFICATIONS (ntfId) ON DELETE CASCADE;

ALTER TABLE USRNTFRELATIONS DROP CONSTRAINT fk_usrnNotifiedAccId;
ALTER TABLE USRNTFRELATIONS DROP CONSTRAINT fk_usrnNotificationId;
ALTER TABLE USRNTFRELATIONS ADD CONSTRAINT fk_usrnNotifiedAccId FOREIGN KEY (usrnNotifiedAccId) REFERENCES USERACCS (userId) ON DELETE CASCADE;
ALTER TABLE USRNTFRELATIONS ADD CONSTRAINT fk_usrnNotificationId FOREIGN KEY (usrnNotificationId) REFERENCES NOTIFICATIONS (ntfId) ON DELETE CASCADE;