ALTER TABLE USERLOGS MODIFY (ULOGSOURCEIP VARCHAR2(40));
ALTER TABLE USERGROUPLOGS MODIFY (UGLOGSOURCEIP VARCHAR2(40));
ALTER TABLE ITEMLOGS MODIFY (ILOGSOURCEIP VARCHAR2(40));
ALTER TABLE ITEMGROUPLOGS MODIFY (IGLOGSOURCEIP VARCHAR2(40));
