-- USER SQL
CREATE USER EsseR IDENTIFIED BY 118887MgT ;

-- QUOTAS
ALTER USER EsseR QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "CONNECT" TO EsseR ;
ALTER USER EsseR DEFAULT ROLE "CONNECT";

-- SYSTEM PRIVILEGES
GRANT CREATE LIBRARY TO EsseR ;
GRANT CREATE TRIGGER TO EsseR ;
GRANT CREATE ANY DIRECTORY TO EsseR ;
GRANT CREATE MATERIALIZED VIEW TO EsseR ;
GRANT CREATE INDEXTYPE TO EsseR ;
GRANT CREATE VIEW TO EsseR ;
GRANT CREATE SESSION TO EsseR ;
GRANT CREATE RULE TO EsseR ;
GRANT CREATE TABLE TO EsseR ;
GRANT CREATE TYPE TO EsseR ;
GRANT CREATE TABLESPACE TO EsseR ;
GRANT CREATE SYNONYM TO EsseR ;
GRANT CREATE SEQUENCE TO EsseR ;
GRANT CREATE RULE SET TO EsseR ;
GRANT CREATE PROCEDURE TO EsseR ;
GRANT EXECUTE ON UTL_FILE TO EsseR;
