-- Creation of the database; Sequences Phase (Step3);
CREATE SEQUENCE incr_useraccs start with 1 INCREMENT BY 1;
/
CREATE SEQUENCE incr_itmgrps START WITH 1 INCREMENT BY 1;
/
CREATE SEQUENCE incr_itms START WITH 1 INCREMENT BY 1;
/
CREATE SEQUENCE incr_usergrps START WITH 1 INCREMENT BY 1;
/
CREATE SEQUENCE incr_grprels START WITH 1 INCREMENT BY 1;
/
CREATE SEQUENCE incr_itmgrpowns START WITH 1 INCREMENT BY 1;
/
CREATE SEQUENCE incr_usrgrplogs START WITH 1 INCREMENT BY 1;
/
CREATE SEQUENCE incr_itmgrplogs START WITH 1 INCREMENT BY 1;
/
CREATE SEQUENCE incr_usrlogs START WITH 1 INCREMENT BY 1;
/
CREATE SEQUENCE incr_itmlogs START WITH 1 INCREMENT BY 1;
/
CREATE SEQUENCE incr_autorep START WITH 1 INCREMENT BY 1;
/
CREATE SEQUENCE incr_notifs START WITH 1 INCREMENT BY 1;
/
CREATE SEQUENCE incr_ugrpntfsrel START WITH 1 INCREMENT BY 1;
/
CREATE SEQUENCE incr_usrntfrel START WITH 1 INCREMENT BY 1;
/
--CREATE SEQUENCE incr_itmowns START WITH 1 INCREMENT BY 1;
--/
COMMIT;
/
