<?php include VIEW . 'home/header.phtml';?>

<div class="main-container">
    <div class="lgn-box">
        <h1 class="main-text"> Recover My Password </h1>
        <form class="lgn-form" action="/recover_password_script.php">
            <p class="main-text"> Type in your username: </p>
            <input class="fill-box" type="text" name="uname" value="" placeholder="Enter Your Username" required="required"/>
		   	<input type="submit" class="lgn-view-btn" value="Sumbit">
            <button type="button" class="lgn-view-btn" onclick="window.location='/index.html'">Cancel</button>
		</form>
    </div>
</div>

<?php include VIEW . 'home/footer.phtml';?>