<?php include VIEW . 'home/header.phtml';?>

<div class="main-container">
    <div class="lgn-box">
        <h1 class="main-text"> Recover My Password </h1>
        <p class="main-text"> The request couldn't be proccesed, due to either not being valid or other technical reasons such as time-outs, corrupted data, etc. </p>
        <button type="button" class="lgn-view-btn" onclick="window.location='/login_forgot.html'">Retry</button>
        <button type="button" class="lgn-view-btn" onclick="window.location='/index.html'">Return</button>
    </div>
</div>

<?php include VIEW . 'home/footer.phtml';?>