<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Logs</title>
    <link rel="stylesheet" type="text/css" href="/assets/normal/css/nav_gmt.css">

    <title>Logs</title>
</head>
<body id="body">

        <div id="nav-mobile-container">
            <p><a href="#mobile_nav" id="access_nav" class="access_aid">Navigation</a></p>
s
            <nav id="mobile_nav">
                <ul>
                    <li><a id="nav-mobile-username">John Doe</a></li>
                    <li><a class="nav-mobile-button" href="../index.phtml">Home</a></li>
                    <li><a class="nav-mobile-button" href="../alerts/alerts.phtml">Alerts</a></li>
                    <li class="active"><a class="nav-mobile-button" href="gs.html">Logs</a></li>
                    <li><a class="nav-mobile-button" href="../items/items.phtml">Products</a></li>
                    <li><a class="nav-mobile-button" href="../users/view.users.html">Groups</a></li>
                    <li><a class="nav-mobile-button" href="#">Generate Report</a></li>
                    <li><a class="nav-mobile-button" href="../../home/login/login.phtml">Logout</a></li>
                </ul>
            </nav>

        </div>

        <span class="sidenav">
            <a id="nav-username">John Doe</a>
            <a class="nav-button" href="../index.phtml">Home</a>
            <a class="nav-button" href="../alerts/alerts.phtml">Alerts</a>
            <span class="active"><a class="nav-button" href="gs.html">Logs</a></span>
            <a class="nav-button" href="../items/items.phtml">Products</a>
            <a class="nav-button" href="../users/view.users.html">Groups</a>
            <a class="nav-button" href="#">Generate Report</a>
            <a class="nav-button" href="../../home/login/login.phtml">Logout</a>
        </span>   

<div class="main-div">

    <div class="container">
        <h1>Activity!</h1>
    </div>

    <ul>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
        <li> <u>28-02-2018 19:00:01</u>
            <span style="color: blue"><strong>2</strong></span> <a href="#">Coffee bags</a> were taken by
            <a href="#">Office 5</a> !
            <span style="color: red"><strong>0</strong></span> <a href="#">Coffee bags</a> left!</li>
    </ul>
</div>

<div id="footer">
    <a href="#" class="footer_elem">Random</a>
    <a href="#" class="footer_elem">Sitemap</a>
    <a href="#" class="footer_elem">© 2018 Esser</a>
</div>

</body>
<script src="/assets/normal/js/nav_gmt.js"></script>
</html>