<?php include VIEW . 'user/header.phtml';?>

    <div id="main-first-row-container">
        <div id="page-title">
            <h1>Activity</h1>
        </div>
    </div>

    <div id="main-second-row-container">
    <div class="container">
        <ul>
            <?php
            if(!empty($this->view_data["userlogs"]))
            {
                foreach ($this->view_data["userlogs"] as $log)
                {
                    echo "<li> <u>" . $log["uLogCreatedAt"] . "</u> " . $log["uLogDescription"] . "</li>";
                }
            }
            else
            {
                echo "<li> <u>There are no activity logs! </u></li>";
            }
            ?>
        </ul>
    </div>
    </div>

<?php include VIEW . 'user/footer.phtml';?>