<?php include VIEW . 'home/header.phtml';?>

    <div class="main-container">
        <div class="lgn-box">
            <h1 class="main-text"> Change Password </h1>
            <form class="lgn-form" action="/login/password/change" method="POST">
                <input type="hidden" id="username"  name="username" value="<?php echo $this->view_data["user_array"]["userName"]?>">
                <input type="hidden" id="hash"      name="hash"     value="<?php echo $this->view_data["user_array"]["userPass"]?>">
                <p class="main-text"> New Password </p>
                <input class="fill-box" type="password" name="new_password" value="" placeholder="Enter Your Password" required="required"/>
                <p class="main-text"> Confirm New Password </p>
                <input class="fill-box" type="password" name="confirm_new_password" value="" placeholder="Re-enter Your Password" required="required"/>
                <input type="submit" class="lgn-view-btn" value="Change">
                <button type="button" class="lgn-view-btn" onclick="window.location='/'">Homepage</button>
            </form>
        </div>
    </div>

<?php include VIEW . 'home/footer.phtml';?>