<?php include VIEW . 'admincp/header.phtml';?>

<?php include VIEW . 'admincp/menu/header_bar.phtml';?>

<div class="admcp-tables-body">
    <?php include VIEW . 'admincp/menu/menu.phtml';?>
    <div class="admcp-rt-box">
        <div class="admcp-rt-cnt-box">
            <div class="admcp-rt-content">
                <div class="dshb-cnt-line">
                    <div class="info">
                        <label> User count: </label>
                    </div>
                    <div class="info-result">
                        <output class="dshb-online-usrs"><?php echo $this->view_data['onlineUsers']?> (Online)</output>
                        <label class="separator"> / </label>
                        <output class="dshb-total-usrs"><?php echo $this->view_data['totalUsers']?> (Total)</output>
                    </div>
                </div>
                <div class="dshb-cnt-line">
                    <div class="info">
                        <label> Last login date and time: </label>
                    </div>
                    <div class="info-result">
                        <output class="rslt-datetime"> <?php echo $this->view_data['lastLogin'] ?> </output>
                        <output class="rslt-timezone"> <?php echo $this->view_data['timeZone'] ?> </output>
                    </div>
                </div>
                <div class="dshb-cnt-line">
                    <div class="info">
                        <label> Latest DB backup time: </label>
                    </div>
                    <div class="info-result">
                        <output class="rslt-datetime" value="getLastDBBkupTime('this.database')"> 19/02/2018 at 19:42:323.870 </output>
                        <output class="rslt-timezone" value="getSrvTimeZone()"> UMT+2 @Bucharest Time </output>
                    </div>
                </div>
                <div class="dshb-cnt-line">
                    <div class="info">
                        <label> Total number of product groups: </label>
                    </div>
                    <div class="info-result">
                        <output class="prd-result" value="getCountProductGroups()" id="prd-grp-nr"> 3000 </output>
                    </div>
                </div>
                <div class="dshb-cnt-line">
                    <div class="info">
                        <label> Average number of products per group: </label>
                    </div>
                    <div class="info-result">
                        <output class="prd-result" value="getAvgProductCountPerGroup()" id="prd-grp-avg"> 3200000 </output>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php include VIEW . 'admincp/footer.phtml';?>
