<?php
/**
 * Created by PhpStorm.
 * User: ghita
 * Date: 5/26/2018
 * Time: 1:37 PM
 */ ?>

<!DOCTYPE html>
<html>
<head>
    <link rel="icon" href="/resources/images/global/favicon.png" />
    <link rel="stylesheet" href="/resources/css/admincp/admincp.css" />
    <meta charset="utf-8">
    <meta name="author" content="Bugeag George Tiberiu">
    <meta name="description" content="Web Technologies Project">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo (isset($this->page_title) ? $this->page_title : "Welcome!"); ?></title>
</head>
<body>