<?php include VIEW . 'admincp/header.phtml';?>

        <div class="admcp-header-bar"> 
            <button type="button" class="back-to-website" onclick="window.location='/'"> Back to Website! </button>
        </div>
        <div class="main-container">
            <h1 class="main-text"> Welcome to AdminCP </h1>
            <div class="lgn-box">
                <h2 class="main-text"> Login Menu:</h2>
                <form class="lgn-form" action="/admincp/login">       <!-- TO DO: handle from controller! -->
                    <p class="main-text"> Username: </p>
                    <input class="fill-box" type="text" name="uname" value="" placeholder="Enter Your Username" required="required"/>	  	
                    <p class="main-text"> Password: </p>
                    <input class="fill-box" type="password" name="psw" value="" placeholder="Enter Your Password" required="required"/>
                    <br />
                    <output class="bad-credentials">The username and/or password are/is incorrect!</output>
		  	   	    <input type="submit" class="admcp-lgn-view-btn" value="Login">
                    <button type="button" class="admcp-lgn-view-btn" onclick="window.location='/'">Go Back</button>
		  	   </form>
            </div>
        </div>

<?php include VIEW . 'admincp/footer.phtml';?>
